countries = {
    "austria": "Австрия",
    "belgium": "Бельгия",
    "denmark": "Дания",
    "estonia": "Эстония",
    "finland": "Финляндия",
    "france": "Франция",
    "germany": "Германия",
    "iceland": "Исландия",
    "ireland": "Ирландия",
    "israel": "Израиль",
    "italy": "Италия",
    "japan": "Япония",
    "latvia": "Латвия",
    "lithuania": "Литва",
    "luxembourg": "Люксембург",
    "netherlands": "Нидерланды",
    "norway": "Норвегия",
    "portugal": "Португалия",
    "russia": "Россия",
    "singapore": "Сингапур",
    "south_korea": "Южная Корея",
    "spain": "Испания",
    "sweden": "Швеция",
    "switzerland": "Швейцария",
    "taiwan": "Тайвань",
    "united_kingdom": "Великобритания"
}
reversed_countries = {v: k for k, v in countries.items()}